In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder

In [2]:
data = pd.read_csv(
    "/Users/gabrielaslomiany/GIT/Alzheimer Detection/data/data.csv",
    sep=None,
    engine="python"
)
print(data.shape)
data.head()

(1737, 361)

,﻿RID,Test_data,Age,Gender,Year_education,Ethnicity,Race,Marital_status,High_risk_ApoE4,Ventricles,...,Cortical Thickness Standard Deviation of RightLingual,Volume (Cortical Parcellation) of RightMedialOrbitofrontal,Surface Area of RightMedialOrbitofrontal,Cortical Thickness Average of RightMedialOrbitofrontal,Cortical Thickness Standard Deviation of RightMedialOrbitofrontal,Volume (Cortical Parcellation) of RightMiddleTemporal,Surface Area of RightMiddleTemporal,Cortical Thickness Average of RightMiddleTemporal,Cortical Thickness Standard Deviation of RightMiddleTemporal,Volume (WM Parcellation) of FourthVentricle
0,2,0,"74,3",Male,16,Not Hisp/Latino,White,Married,0.0,118233.0,...,"0,694",3835,1622,"2,077","0,746",15683,4272,"3,028","0,649",4396
1,3,0,"81,3",Male,18,Not Hisp/Latino,White,Married,1.0,84599.0,...,"0,591",3681,1734,"1,942","0,696",10387,3316,"2,545","0,686",3304
2,4,1,"67,5",Male,10,Hisp/Latino,White,Married,0.0,39605.0,...,"0,588",4060,1728,"2,18","0,607",11156,3598,"2,67","0,631",1338
3,5,0,"73,7",Male,16,Not Hisp/Latino,White,Married,0.0,34062.0,...,"0,628",5180,1868,"2,543","0,709",11579,3387,"2,911","0,66",1623
4,6,0,"80,4",Female,13,Not Hisp/Latino,White,Married,0.0,39826.0,...,"0,631",3078,1241,"2,141","0,701",9641,2781,"2,9","0,727",1035

In [3]:
cognitive = pd.read_csv(
    "/Users/gabrielaslomiany/GIT/Alzheimer Detection/data/cognitive_score.csv",
    sep=None,
    engine="python"
)
print(cognitive.shape)
cognitive.head()

(1737, 10)

,﻿RID,Test_data,CDRSB,ADAS11,ADAS13,MMSE,RAVLT_immediate,RAVLT_learning,RAVLT_forgetting,RAVLT_perc_forgetting
0,2,0,0,"10,67","18,67",28,44.0,4.0,6.0,"54,5455"
1,3,0,"4,5",22,31,20,22.0,1.0,4.0,100
2,4,1,1,"14,33","21,33",27,37.0,7.0,4.0,"36,3636"
3,5,0,0,"8,67","14,67",29,37.0,4.0,4.0,"44,4444"
4,6,0,"0,5","18,67","25,67",25,30.0,1.0,5.0,"83,3333"

In [4]:
diagnosis = pd.read_csv(
    "/Users/gabrielaslomiany/GIT/Alzheimer Detection/data/diagnosis_target.csv",
    sep=None,
    engine="python"
)
print(diagnosis.shape)
diagnosis.head()

(1737, 4)

   ﻿RID  Test_data Diagnosis  FDG_PET
0     2          0        CN  1,36926
1     3          0        AD  1,09079
2     4          1      LMCI      NaN
3     5          0        CN  1,29799
4     6          0      LMCI      NaN

### Missing data

##### Data datframe

In [5]:
data.isna().sum()

﻿RID                                                            0
Test_data                                                       0
Age                                                             0
Gender                                                          0
Year_education                                                  0
                                                               ..
Volume (Cortical Parcellation) of RightMiddleTemporal           0
Surface Area of RightMiddleTemporal                             0
Cortical Thickness Average of RightMiddleTemporal               0
Cortical Thickness Standard Deviation of RightMiddleTemporal    0
Volume (WM Parcellation) of FourthVentricle                     0
Length: 361, dtype: int64

As data dataframe has 361 columns, checking NaN's is much simpler with function below. Data's share is (1737, 361), and count highest count of missing values is 291, which is about 17%.

In [6]:
missing_values = data.isna().sum()
missing_values = missing_values[missing_values > 0]

missing_values

High_risk_ApoE4                                                  12
Ventricles                                                       82
Hippocampus                                                     248
WholeBrain                                                       48
Entorhinal                                                      271
Fusiform                                                        271
MidTemp                                                         271
Intra cranial volume                                             15
Volume (WM Parcellation) of RightVessel                           2
Volume (Cortical Parcellation) of LeftEntorhinal                  1
Surface Area of LeftEntorhinal                                    1
Cortical Thickness Average of LeftEntorhinal                      1
Cortical Thickness Standard Deviation of LeftEntorhinal           1
Volume (Cortical Parcellation) of LeftParahippocampal             1
Surface Area of LeftParahippocampal                               1
Cortical Thickness Average of LeftParahippocampal                 1
Cortical Thickness Standard Deviation of LeftParahippocampal      1
Volume (WM Parcellation) of LeftVessel                            2
Volume (WM Parcellation) of FifthVentricle                      291
dtype: int64

In [7]:
data[['Hippocampus','Entorhinal', 'Fusiform', 'MidTemp', 'Volume (WM Parcellation) of FifthVentricle']].dtypes

Hippocampus                                   float64
Entorhinal                                    float64
Fusiform                                      float64
MidTemp                                       float64
Volume (WM Parcellation) of FifthVentricle        str
dtype: object

Hippocampus, Entorhinal, Fusiform, MidTemp --> replace with mean, as their dtype is float
Volume (WM Parcellation) of FifthVentricle --> drop

In [8]:
columns = ["Entorhinal", "Fusiform", "MidTemp"]

data[columns] = data[columns].fillna(data[columns].mean())

In [9]:
data.dropna(inplace=True)

In [10]:
data.isna().sum()

﻿RID                                                            0
Test_data                                                       0
Age                                                             0
Gender                                                          0
Year_education                                                  0
                                                               ..
Volume (Cortical Parcellation) of RightMiddleTemporal           0
Surface Area of RightMiddleTemporal                             0
Cortical Thickness Average of RightMiddleTemporal               0
Cortical Thickness Standard Deviation of RightMiddleTemporal    0
Volume (WM Parcellation) of FourthVentricle                     0
Length: 361, dtype: int64

##### Cognitive dataframe

In [11]:
cognitive.isna().sum()

﻿RID                      0
Test_data                 0
CDRSB                     0
ADAS11                    5
ADAS13                   14
MMSE                      0
RAVLT_immediate           6
RAVLT_learning            6
RAVLT_forgetting          6
RAVLT_perc_forgetting    11
dtype: int64

Cognitive dataframe shape is (1737, 10), since missing values are less than 5% I will drop it

In [12]:
cognitive.dropna(inplace=True)

In [13]:
cognitive.isna().sum().sum()

np.int64(0)

##### Diagnosis dataframe

In [14]:
print(diagnosis.shape)
diagnosis.isna().sum()

(1737, 4)

﻿RID           0
Test_data      0
Diagnosis      0
FDG_PET      434
dtype: int64

In [15]:
diagnosis.dtypes

﻿RID         int64
Test_data    int64
Diagnosis      str
FDG_PET        str
dtype: object

In [17]:
# Even though NANs are big portion of FDG_PET after numerous attempts I decided to drop it

diagnosis.dropna()

      ﻿RID  Test_data Diagnosis  FDG_PET
0        2          0        CN  1,36926
1        3          0        AD  1,09079
3        5          0        CN  1,29799
6        8          0        CN  1,27628
7       10          0        AD  1,11881
...    ...        ...       ...      ...
1730  5275          0        AD  1,03993
1731  5282          0       SMC  1,13549
1732  5287          0       SMC  1,58312
1733  5295          0       SMC  1,16317
1734  5296          0       SMC  1,42926

[1303 rows x 4 columns]

##### Merging dataframes

In [ ]:
merged = pd.merge(diagnosis, cognitive, on="Test_data", how="inner")
df = pd.merge(merged, data, on="Test_data", how="inner")
df.head()

In [22]:
print(diagnosis.columns.tolist())

['\ufeffRID', 'Test_data', 'Diagnosis', 'FDG_PET']

In [23]:
print(cognitive.columns.tolist())

['\ufeffRID', 'Test_data', 'CDRSB', 'ADAS11', 'ADAS13', 'MMSE', 'RAVLT_immediate', 'RAVLT_learning', 'RAVLT_forgetting', 'RAVLT_perc_forgetting']

In [25]:
print(data.columns.tolist())

['\ufeffRID', 'Test_data', 'Age', 'Gender', 'Year_education', 'Ethnicity', 'Race', 'Marital_status', 'High_risk_ApoE4', 'Ventricles', 'Hippocampus', 'WholeBrain', 'Entorhinal', 'Fusiform', 'MidTemp', 'Intra cranial volume', 'Volume (WM Parcellation) of RightPallidum', 'Volume (Cortical Parcellation) of RightParacentral', 'Surface Area of RightParacentral', 'Cortical Thickness Average of RightParacentral', 'Cortical Thickness Standard Deviation of RightParacentral', 'Volume (Cortical Parcellation) of RightParahippocampal', 'Surface Area of RightParahippocampal', 'Cortical Thickness Average of RightParahippocampal', 'Cortical Thickness Standard Deviation of RightParahippocampal', 'Volume (Cortical Parcellation) of RightParsOpercularis', 'Surface Area of RightParsOpercularis', 'Cortical Thickness Average of RightParsOpercularis', 'Cortical Thickness Standard Deviation of RightParsOpercularis', 'Volume (Cortical Parcellation) of RightParsOrbitalis', 'Surface Area of RightParsOrbitalis', 'Cortical Thickness Average of RightParsOrbitalis', 'Cortical Thickness Standard Deviation of RightParsOrbitalis', 'Volume (Cortical Parcellation) of RightParsTriangularis', 'Surface Area of RightParsTriangularis', 'Cortical Thickness Average of RightParsTriangularis', 'Cortical Thickness Standard Deviation of RightParsTriangularis', 'Volume (Cortical Parcellation) of RightPericalcarine', 'Surface Area of RightPericalcarine', 'Cortical Thickness Average of RightPericalcarine', 'Cortical Thickness Standard Deviation of RightPericalcarine', 'Volume (Cortical Parcellation) of RightPostcentral', 'Surface Area of RightPostcentral', 'Cortical Thickness Average of RightPostcentral', 'Cortical Thickness Standard Deviation of RightPostcentral', 'Volume (Cortical Parcellation) of RightPosteriorCingulate', 'Surface Area of RightPosteriorCingulate', 'Cortical Thickness Average of RightPosteriorCingulate', 'Cortical Thickness Standard Deviation of RightPosteriorCingulate', 'Volume (Cortical Parcellation) of Icv', 'Volume (Cortical Parcellation) of RightPrecentral', 'Surface Area of RightPrecentral', 'Cortical Thickness Average of RightPrecentral', 'Cortical Thickness Standard Deviation of RightPrecentral', 'Volume (Cortical Parcellation) of RightPrecuneus', 'Surface Area of RightPrecuneus', 'Cortical Thickness Average of RightPrecuneus', 'Cortical Thickness Standard Deviation of RightPrecuneus', 'Volume (WM Parcellation) of RightPutamen', 'Volume (Cortical Parcellation) of RightRostralAnteriorCingulate', 'Surface Area of RightRostralAnteriorCingulate', 'Cortical Thickness Average of RightRostralAnteriorCingulate', 'Cortical Thickness Standard Deviation of RightRostralAnteriorCingulate', 'Volume (Cortical Parcellation) of RightRostralMiddleFrontal', 'Surface Area of RightRostralMiddleFrontal', 'Cortical Thickness Average of RightRostralMiddleFrontal', 'Cortical Thickness Standard Deviation of RightRostralMiddleFrontal', 'Volume (Cortical Parcellation) of RightSuperiorFrontal', 'Surface Area of RightSuperiorFrontal', 'Cortical Thickness Average of RightSuperiorFrontal', 'Cortical Thickness Standard Deviation of RightSuperiorFrontal', 'Volume (Cortical Parcellation) of RightSuperiorParietal', 'Surface Area of RightSuperiorParietal', 'Cortical Thickness Average of RightSuperiorParietal', 'Cortical Thickness Standard Deviation of RightSuperiorParietal', 'Volume (Cortical Parcellation) of RightSuperiorTemporal', 'Surface Area of RightSuperiorTemporal', 'Cortical Thickness Average of RightSuperiorTemporal', 'Cortical Thickness Standard Deviation of RightSuperiorTemporal', 'Volume (Cortical Parcellation) of RightSupramarginal', 'Surface Area of RightSupramarginal', 'Cortical Thickness Average of RightSupramarginal', 'Cortical Thickness Standard Deviation of RightSupramarginal', 'Volume (Cortical Parcellation) of RightTemporalPole', 'Surface Area of RightTemporalPole', 'Cortical Thickness Average of RightTemporalPole', 'Cortical Thickness Standard Deviation of RightTemporalPole', 'Volume (WM Parcellation) of LeftAccumbensArea', 'Volume (WM Parcellation) of RightThalamus', 'Volume (Cortical Parcellation) of RightTransverseTemporal', 'Surface Area of RightTransverseTemporal', 'Cortical Thickness Average of RightTransverseTemporal', 'Cortical Thickness Standard Deviation of RightTransverseTemporal', 'Volume (WM Parcellation) of RightUndetermined', 'Volume (Cortical Parcellation) of RightUnknown', 'Surface Area of RightUnknown', 'Cortical Thickness Average of RightUnknown', 'Cortical Thickness Standard Deviation of RightUnknown', 'Volume (WM Parcellation) of RightVentralDC', 'Volume (WM Parcellation) of RightVessel', 'Volume (WM Parcellation) of RightWMHypoIntensities', 'Volume (WM Parcellation) of ThirdVentricle', 'Volume (WM Parcellation) of WMHypoIntensities', 'Volume (Cortical Parcellation) of LeftInsula', 'Surface Area of LeftInsula', 'Cortical Thickness Average of LeftInsula', 'Cortical Thickness Standard Deviation of LeftInsula', 'Volume (WM Parcellation) of LeftAmygdala', 'Volume (Cortical Parcellation) of RightInsula', 'Surface Area of RightInsula', 'Cortical Thickness Average of RightInsula', 'Cortical Thickness Standard Deviation of RightInsula', 'Volume (Cortical Parcellation) of LeftBankssts', 'Surface Area of LeftBankssts', 'Cortical Thickness Average of LeftBankssts', 'Cortical Thickness Standard Deviation of LeftBankssts', 'Volume (Cortical Parcellation) of LeftCaudalAnteriorCingulate', 'Surface Area of LeftCaudalAnteriorCingulate', 'Cortical Thickness Average of LeftCaudalAnteriorCingulate', 'Cortical Thickness Standard Deviation of LeftCaudalAnteriorCingulate', 'Volume (Cortical Parcellation) of LeftCaudalMiddleFrontal', 'Surface Area of LeftCaudalMiddleFrontal', 'Cortical Thickness Average of LeftCaudalMiddleFrontal', 'Cortical Thickness Standard Deviation of LeftCaudalMiddleFrontal', 'Volume (WM Parcellation) of LeftCaudate', 'Volume (WM Parcellation) of LeftCerebellumCortex', 'Volume (WM Parcellation) of LeftCerebellumWM', 'Volume (WM Parcellation) of LeftCerebralCortex', 'Volume (WM Parcellation) of Brainstem', 'Volume (WM Parcellation) of LeftCerebralWM', 'Volume (WM Parcellation) of LeftChoroidPlexus', 'Volume (Cortical Parcellation) of LeftCorpusCallosum', 'Surface Area of LeftCorpusCallosum', 'Cortical Thickness Average of LeftCorpusCallosum', 'Cortical Thickness Standard Deviation of LeftCorpusCallosum', 'Volume (Cortical Parcellation) of LeftCuneus', 'Surface Area of LeftCuneus', 'Cortical Thickness Average of LeftCuneus', 'Cortical Thickness Standard Deviation of LeftCuneus', 'Volume (Cortical Parcellation) of LeftEntorhinal', 'Surface Area of LeftEntorhinal', 'Cortical Thickness Average of LeftEntorhinal', 'Cortical Thickness Standard Deviation of LeftEntorhinal', 'Volume (Cortical Parcellation) of LeftFrontalPole', 'Surface Area of LeftFrontalPole', 'Cortical Thickness Average of LeftFrontalPole', 'Cortical Thickness Standard Deviation of LeftFrontalPole', 'Volume (Cortical Parcellation) of LeftFusiform', 'Surface Area of LeftFusiform', 'Cortical Thickness Average of LeftFusiform', 'Cortical Thickness Standard Deviation of LeftFusiform', 'Surface Area of LeftHemisphere', 'Volume (Cortical Parcellation) of LeftHemisphereWM', 'Volume (WM Parcellation) of LeftHippocampus', 'Volume (WM Parcellation) of CorpusCallosumAnterior', 'Volume (WM Parcellation) of LeftInferiorLateralVentricle', 'Volume (Cortical Parcellation) of LeftInferiorParietal', 'Surface Area of LeftInferiorParietal', 'Cortical Thickness Average of LeftInferiorParietal', 'Cortical Thickness Standard Deviation of LeftInferiorParietal', 'Volume (Cortical Parcellation) of LeftInferiorTemporal', 'Surface Area of LeftInferiorTemporal', 'Cortical Thickness Average of LeftInferiorTemporal', 'Cortical Thickness Standard Deviation of LeftInferiorTemporal', 'Volume (WM Parcellation) of LeftInterior', 'Volume (Cortical Parcellation) of LeftIsthmusCingulate', 'Surface Area of LeftIsthmusCingulate', 'Cortical Thickness Average of LeftIsthmusCingulate', 'Cortical Thickness Standard Deviation of LeftIsthmusCingulate', 'Volume (Cortical Parcellation) of LeftLateralOccipital', 'Surface Area of LeftLateralOccipital', 'Cortical Thickness Average of LeftLateralOccipital', 'Cortical Thickness Standard Deviation of LeftLateralOccipital', 'Volume (Cortical Parcellation) of LeftLateralOrbitofrontal', 'Surface Area of LeftLateralOrbitofrontal', 'Cortical Thickness Average of LeftLateralOrbitofrontal', 'Cortical Thickness Standard Deviation of LeftLateralOrbitofrontal', 'Volume (WM Parcellation) of LeftLateralVentricle', 'Volume (Cortical Parcellation) of LeftLingual', 'Surface Area of LeftLingual', 'Cortical Thickness Average of LeftLingual', 'Cortical Thickness Standard Deviation of LeftLingual', 'Volume (Cortical Parcellation) of LeftMedialOrbitofrontal', 'Surface Area of LeftMedialOrbitofrontal', 'Cortical Thickness Average of LeftMedialOrbitofrontal', 'Cortical Thickness Standard Deviation of LeftMedialOrbitofrontal', 'Volume (WM Parcellation) of CorpusCallosumCentral', 'Volume (Cortical Parcellation) of LeftMiddleTemporal', 'Surface Area of LeftMiddleTemporal', 'Cortical Thickness Average of LeftMiddleTemporal', 'Cortical Thickness Standard Deviation of LeftMiddleTemporal', 'Volume (WM Parcellation) of LeftNonWMHypoIntensities', 'Volume (WM Parcellation) of LeftPallidum', 'Volume (Cortical Parcellation) of LeftParacentral', 'Surface Area of LeftParacentral', 'Cortical Thickness Average of LeftParacentral', 'Cortical Thickness Standard Deviation of LeftParacentral', 'Volume (Cortical Parcellation) of LeftParahippocampal', 'Surface Area of LeftParahippocampal', 'Cortical Thickness Average of LeftParahippocampal', 'Cortical Thickness Standard Deviation of LeftParahippocampal', 'Volume (Cortical Parcellation) of LeftParsOpercularis', 'Surface Area of LeftParsOpercularis', 'Cortical Thickness Average of LeftParsOpercularis', 'Cortical Thickness Standard Deviation of LeftParsOpercularis', 'Volume (Cortical Parcellation) of LeftParsOrbitalis', 'Surface Area of LeftParsOrbitalis', 'Cortical Thickness Average of LeftParsOrbitalis', 'Cortical Thickness Standard Deviation of LeftParsOrbitalis', 'Volume (Cortical Parcellation) of LeftParsTriangularis', 'Surface Area of LeftParsTriangularis', 'Cortical Thickness Average of LeftParsTriangularis', 'Cortical Thickness Standard Deviation of LeftParsTriangularis', 'Volume (Cortical Parcellation) of LeftPericalcarine', 'Surface Area of LeftPericalcarine', 'Cortical Thickness Average of LeftPericalcarine', 'Cortical Thickness Standard Deviation of LeftPericalcarine', 'Volume (Cortical Parcellation) of LeftPostcentral', 'Surface Area of LeftPostcentral', 'Cortical Thickness Average of LeftPostcentral', 'Cortical Thickness Standard Deviation of LeftPostcentral', 'Volume (WM Parcellation) of CorpusCallosumMidAnterior', 'Volume (Cortical Parcellation) of LeftPosteriorCingulate', 'Surface Area of LeftPosteriorCingulate', 'Cortical Thickness Average of LeftPosteriorCingulate', 'Cortical Thickness Standard Deviation of LeftPosteriorCingulate', 'Volume (Cortical Parcellation) of LeftPrecentral', 'Surface Area of LeftPrecentral', 'Cortical Thickness Average of LeftPrecentral', 'Cortical Thickness Standard Deviation of LeftPrecentral', 'Volume (Cortical Parcellation) of LeftPrecuneus', 'Surface Area of LeftPrecuneus', 'Cortical Thickness Average of LeftPrecuneus', 'Cortical Thickness Standard Deviation of LeftPrecuneus', 'Volume (WM Parcellation) of LeftPutamen', 'Volume (Cortical Parcellation) of LeftRostralAnteriorCingulate', 'Surface Area of LeftRostralAnteriorCingulate', 'Cortical Thickness Average of LeftRostralAnteriorCingulate', 'Cortical Thickness Standard Deviation of LeftRostralAnteriorCingulate', 'Volume (Cortical Parcellation) of LeftRostralMiddleFrontal', 'Surface Area of LeftRostralMiddleFrontal', 'Cortical Thickness Average of LeftRostralMiddleFrontal', 'Cortical Thickness Standard Deviation of LeftRostralMiddleFrontal', 'Volume (Cortical Parcellation) of LeftSuperiorFrontal', 'Surface Area of LeftSuperiorFrontal', 'Cortical Thickness Average of LeftSuperiorFrontal', 'Cortical Thickness Standard Deviation of LeftSuperiorFrontal', 'Volume (Cortical Parcellation) of LeftSuperiorParietal', 'Surface Area of LeftSuperiorParietal', 'Cortical Thickness Average of LeftSuperiorParietal', 'Cortical Thickness Standard Deviation of LeftSuperiorParietal', 'Volume (Cortical Parcellation) of LeftSuperiorTemporal', 'Surface Area of LeftSuperiorTemporal', 'Cortical Thickness Average of LeftSuperiorTemporal', 'Cortical Thickness Standard Deviation of LeftSuperiorTemporal', 'Volume (Cortical Parcellation) of LeftSupramarginal', 'Surface Area of LeftSupramarginal', 'Cortical Thickness Average of LeftSupramarginal', 'Cortical Thickness Standard Deviation of LeftSupramarginal', 'Volume (WM Parcellation) of CorpusCallosumMidPosterior', 'Volume (Cortical Parcellation) of LeftTemporalPole', 'Surface Area of LeftTemporalPole', 'Cortical Thickness Average of LeftTemporalPole', 'Cortical Thickness Standard Deviation of LeftTemporalPole', 'Volume (WM Parcellation) of LeftThalamus', 'Volume (Cortical Parcellation) of LeftTransverseTemporal', 'Surface Area of LeftTransverseTemporal', 'Cortical Thickness Average of LeftTransverseTemporal', 'Cortical Thickness Standard Deviation of LeftTransverseTemporal', 'Volume (WM Parcellation) of LeftUndetermined', 'Volume (Cortical Parcellation) of LeftUnknown', 'Surface Area of LeftUnknown', 'Cortical Thickness Average of LeftUnknown', 'Cortical Thickness Standard Deviation of LeftUnknown', 'Volume (WM Parcellation) of LeftVentralDC', 'Volume (WM Parcellation) of LeftVessel', 'Volume (WM Parcellation) of LeftWMHypoIntensities', 'Volume (WM Parcellation) of NonWMHypoIntensities', 'Volume (WM Parcellation) of OpticChiasm', 'Volume (WM Parcellation) of CorpusCallosumPosterior', 'Volume (WM Parcellation) of RightAccumbensArea', 'Volume (WM Parcellation) of RightAmygdala', 'Volume (Cortical Parcellation) of RightBankssts', 'Surface Area of RightBankssts', 'Cortical Thickness Average of RightBankssts', 'Cortical Thickness Standard Deviation of RightBankssts', 'Volume (Cortical Parcellation) of RightCaudalAnteriorCingulate', 'Surface Area of RightCaudalAnteriorCingulate', 'Cortical Thickness Average of RightCaudalAnteriorCingulate', 'Cortical Thickness Standard Deviation of RightCaudalAnteriorCingulate', 'Volume (Cortical Parcellation) of RightCaudalMiddleFrontal', 'Surface Area of RightCaudalMiddleFrontal', 'Cortical Thickness Average of RightCaudalMiddleFrontal', 'Cortical Thickness Standard Deviation of RightCaudalMiddleFrontal', 'Volume (WM Parcellation) of RightCaudate', 'Volume (WM Parcellation) of RightCerebellumCortex', 'Volume (WM Parcellation) of RightCerebellumWM', 'Volume (WM Parcellation) of RightCerebralCortex', 'Volume (WM Parcellation) of RightCerebralWM', 'Volume (WM Parcellation) of Csf', 'Volume (WM Parcellation) of RightChoroidPlexus', 'Volume (Cortical Parcellation) of RightCorpusCallosum', 'Surface Area of RightCorpusCallosum', 'Cortical Thickness Average of RightCorpusCallosum', 'Cortical Thickness Standard Deviation of RightCorpusCallosum', 'Volume (Cortical Parcellation) of RightCuneus', 'Surface Area of RightCuneus', 'Cortical Thickness Average of RightCuneus', 'Cortical Thickness Standard Deviation of RightCuneus', 'Volume (Cortical Parcellation) of RightEntorhinal', 'Surface Area of RightEntorhinal', 'Cortical Thickness Average of RightEntorhinal', 'Cortical Thickness Standard Deviation of RightEntorhinal', 'Volume (Cortical Parcellation) of RightFrontalPole', 'Surface Area of RightFrontalPole', 'Cortical Thickness Average of RightFrontalPole', 'Cortical Thickness Standard Deviation of RightFrontalPole', 'Volume (Cortical Parcellation) of RightFusiform', 'Surface Area of RightFusiform', 'Cortical Thickness Average of RightFusiform', 'Cortical Thickness Standard Deviation of RightFusiform', 'Surface Area of RightHemisphere', 'Volume (Cortical Parcellation) of RightHemisphereWM', 'Volume (WM Parcellation) of RightHippocampus', 'Volume (WM Parcellation) of RightInferiorLateralVentricle', 'Volume (WM Parcellation) of FifthVentricle', 'Volume (Cortical Parcellation) of RightInferiorParietal', 'Surface Area of RightInferiorParietal', 'Cortical Thickness Average of RightInferiorParietal', 'Cortical Thickness Standard Deviation of RightInferiorParietal', 'Volume (Cortical Parcellation) of RightInferiorTemporal', 'Surface Area of RightInferiorTemporal', 'Cortical Thickness Average of RightInferiorTemporal', 'Cortical Thickness Standard Deviation of RightInferiorTemporal', 'Volume (WM Parcellation) of RightInterior', 'Volume (Cortical Parcellation) of RightIsthmusCingulate', 'Surface Area of RightIsthmusCingulate', 'Cortical Thickness Average of RightIsthmusCingulate', 'Cortical Thickness Standard Deviation of RightIsthmusCingulate', 'Volume (Cortical Parcellation) of RightLateralOccipital', 'Surface Area of RightLateralOccipital', 'Cortical Thickness Average of RightLateralOccipital', 'Cortical Thickness Standard Deviation of RightLateralOccipital', 'Volume (Cortical Parcellation) of RightLateralOrbitofrontal', 'Surface Area of RightLateralOrbitofrontal', 'Cortical Thickness Average of RightLateralOrbitofrontal', 'Cortical Thickness Standard Deviation of RightLateralOrbitofrontal', 'Volume (WM Parcellation) of RightLateralVentricle', 'Volume (Cortical Parcellation) of RightLingual', 'Surface Area of RightLingual', 'Cortical Thickness Average of RightLingual', 'Cortical Thickness Standard Deviation of RightLingual', 'Volume (Cortical Parcellation) of RightMedialOrbitofrontal', 'Surface Area of RightMedialOrbitofrontal', 'Cortical Thickness Average of RightMedialOrbitofrontal', 'Cortical Thickness Standard Deviation of RightMedialOrbitofrontal', 'Volume (Cortical Parcellation) of RightMiddleTemporal', 'Surface Area of RightMiddleTemporal', 'Cortical Thickness Average of RightMiddleTemporal', 'Cortical Thickness Standard Deviation of RightMiddleTemporal', 'Volume (WM Parcellation) of FourthVentricle']

##### Standardise numerical columns

In [ ]:
num_col = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
scaler = StandardScaler()
df['num_col'] = scaler.fit_transform(df[num_col])